### ISSUE TITLE
As IDEM I want proxy to sign WC3 response and store in the local storage after I verified my claims

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#226]
https://www.w3.org/TR/vc-data-model/

response fake data - no kyc at this stage

- Given I have added a claims
- When I verify my claims in vendor details screen
- Then return response like below and store in the local storage
 {
    message: string; //signed claim response by proxy (src/service/kycservice.ts)
    result: "completed";
    userId: string;
    thirdPartyVerified: boolean;
}

**Comment by C00p3rb123** [comment]
Seems like the response is not working because a userId is not being created

I completed these two steps:
Given I have added a claims
When I verify my claims in vendor details screen
and the following errors occurred: 

**Error**
![image](https://user-images.githubusercontent.com/48899363/178195158-d2f4713e-7a30-40d7-91ba-f3d812ecfb42.png)

<img width="226" alt="image" src="https://user-images.githubusercontent.com/48899363/178200941-42a68c55-a688-4441-93fa-fb3b72f378b3.png">

**Comment by xiangzhe0812** [comment]
@C00p3rb123 @Mitchell139  Couldn't reproduce the error, its working on my phone.
