### ISSUE TITLE
As IDEM I want the "Verify My Claims" button temporarily disabled on the profile page so the user is prompted to complete the necessary claims & documents

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#434]
"Verify My Claims" button on the profile page is disabled until the user has filled out the claims and documents

Above the "Verify My Claims" button there will be copy that states "Complete your Name and DOB claims and attached Medicare and Driver Licence documents to verify."

## AC1
- Given I have not previously verified (Name, DOB and Email) and attached the specified documents (Medicare and Driver Licence)
- When I fill out the required claims (Name, DOB and Email) and attached the specified documents (Medicare and Driver Licence)
- Then the "Verify My Claims" button will not be disabled

## Claims and documents to be completed 
- Name
- DOB
- Attach at least 2 documents (w/ metadata) Documents defined in #472 

Relates to Ticket #411

**Comment by C00p3rb123** [comment]
Instead of "Complete your Name and DOB claims and attached Medicare and Driver Licence documents to verify." It should be:
"Complete your Name and DOB claims and attach Medicare and Driver Licence documents to verify." Also the version in the app has email - should this be there?


Verify my claims button enabled without a DOB document



https://user-images.githubusercontent.com/48899363/192966807-644e89ac-5133-4054-856d-c269720bcd9c.MP4

**Comment by xiangzhe0812** [comment]
@C00p3rb123  discussed with @Mitchell139  and @amagon270 we decided leave the "Verify my claims button enabled without a DOB document" for now and ask Lucas in the showcase what he wants to do.
