### ISSUE TITLE
Address details need more fields

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#52]
On the profile page under address 

"property Number" is not the right use of words. when asking for an address when signing up users are usually asked to supply the following fields.. 

- UNIT NUMBER
- HOUSE NUMBER
- STREET NAME
- STREET TYPE
- SUBURB
- POSTCODE
- STATE

**Comment by Mitchell139** [comment]
Street address is general used interchangeable with house number etc. https://www.yourdictionary.com/street-address I think what you meant was "street name" or maybe just "street"

**Comment by C00p3rb123** [comment]
On the profile page under address

"property Number" is not the right use of words. when asking for an address when signing up users are usually asked to supply the following fields..

UNIT NUMBER
HOUSE NUMBER
STREET NAME
STREET TYPE
SUBURB
POSTCODE
STATE

As per the original comments, should unit and house number be separate input fields? It might be slightly confusing to someone if they just have a house number. 

Should it be 'Street' Number instead of 'House' Number? Just because it's versatile with more situations. Eg: If someone lives in a unit - they don't have a 'house' number.

**Comment by bitcoinbrisbane** [comment]
> On the profile page under address
> 
> "property Number" is not the right use of words. when asking for an address when signing up users are usually asked to supply the following fields..
> 
> UNIT NUMBER HOUSE NUMBER STREET NAME STREET TYPE SUBURB POSTCODE STATE
> 
> As per the original comments, should unit and house number be separate input fields? It might be slightly confusing to someone if they just have a house number.
> 
> Should it be 'Street' Number instead of 'House' Number? Just because it's versatile with more situations. Eg: If someone lives in a unit - they don't have a 'house' number.

Just have house number, Street, Suburb, Postcode, State

**Comment by JasminFarhi** [comment]
Followed the Brisbane city council format when writing the headings for these. 
https://www.data.brisbane.qld.gov.au/data/dataset/property-address-data/resource/65cb77d7-5795-48da-a37c-6aed4ee774ad
